=== johanoeh/publisher_data_access/src/main/resources/file/test.xsd
<?xml version="1.0"?>
<xs:schema 
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="testspace"
        xmlns:r="testspace"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        elementFormDefault="qualified">
    
     <!-- Importing XHTML namespace -->
  <xs:import namespace="http://www.w3.org/1999/xhtml"
      schemaLocation="http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"/>

    <xs:element name="db">
        <xs:complexType>
            <xs:sequence>
                <!--user elements -->
                <xs:element name="user" type="r:userType" maxOccurs="unbounded"/>  
                <!-- person elements -->
                <xs:element name="person" type="r:personType" maxOccurs="unbounded"/>
                <!-- subject element -->
                <xs:element name="subject" type="r:subjectType" maxOccurs="unbounded" minOccurs="0"/>    
            </xs:sequence>
            <xs:attribute name="dbConnectionString" use="required"/>   
        </xs:complexType>
        
         <!-- keys and references ''''''''''''''''''''''''''''''''''''''''''' -->
         
        <xs:key name="subjectIDKey">
            <xs:selector xpath="r:subject"/>
            <xs:field xpath="@subjectID"/>
        </xs:key>
        
        <xs:keyref name="subjectIDRef" refer="r:subjectIDKey">
            <xs:selector xpath="r:subject/r:chapter"/>
            <xs:field xpath="@subjectID"/>
        </xs:keyref>

         <xs:keyref name="userRef" refer="r:userIDKey">
                       <xs:selector xpath="r:user"/>
                       <xs:field xpath="@userID"/>
         </xs:keyref> 
         
        <xs:key name="userIDKey">
            <xs:selector xpath="r:person"/>
            <xs:field xpath="@userID"/>
        </xs:key>
    </xs:element>
    
    <!-- type definitions '''''''''''''''''''''''''''''''''''''''''''''''''''-->
    
     <xs:complexType name="Html">
        <xs:complexContent>
          <xs:extension base="xhtml:Block">
            <xs:attributeGroup ref="xhtml:attrs"/>
            <xs:attribute name="onload" type="xhtml:Script"/>
            <xs:attribute name="onunload" type="xhtml:Script"/>
          </xs:extension>
        </xs:complexContent>
    </xs:complexType>
     
    <xs:complexType name="userType">
       <xs:attribute name="userID" type="xs:integer" use="required"/>
       <xs:attribute name="userName" type="xs:string" use="required"/>
       <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    <xs:complexType name="personType">
            <xs:attribute name="userID" type="xs:integer" use="required"/>
            <xs:attribute name="firstName" type="xs:string" use="required"/>
            <xs:attribute name="middleName" type="xs:string" use="required"/>
            <xs:attribute name="lastName" type="xs:string" use="required"/>
            <xs:attribute name="email" type="xs:string" use="required"/>
            <xs:attribute name="country" type="xs:string" use="required"/>
            <xs:attribute name="streetAddress" type="xs:string" use="required"/>
            <xs:attribute name="city" type="xs:string" use="required"/>
            <xs:attribute name="postalCode" type="xs:string" use="required"/>
     </xs:complexType> 
     
     <xs:complexType name="subjectType">
             <xs:sequence>
               <xs:element name="descriptionHTML" type="r:Html" maxOccurs="1">   
               </xs:element>
               <xs:element name="chapter" maxOccurs="unbounded" type="r:chapterType"/>
               <xs:element name="quiz" type="r:quizType">  
               </xs:element>
             </xs:sequence>
             <xs:attribute name="subjectID" type="xs:integer"></xs:attribute>
             <xs:attribute name="subjectName" type="xs:string"></xs:attribute>
     </xs:complexType>
     
     <xs:complexType name="chapterType">
         <xs:sequence>
            <xs:element name="contentHTML" type="r:Html" maxOccurs="1">   
            </xs:element>
         </xs:sequence>
         <xs:attribute name="chapterID" type="xs:integer"/>
         <xs:attribute name="subjectID" type="xs:integer"/>
         <xs:attribute name="chapterName" type="xs:string"/>
         <xs:attribute name="priority" type="xs:integer"/>
     </xs:complexType>
     
      <xs:complexType name="quizType">
         <xs:sequence>
             <xs:element name="question" type="r:questionType" >
             </xs:element>
         </xs:sequence>
         <xs:attribute name="quizID" type="xs:integer"/>
         <xs:attribute name="quizName" type="xs:string"/>
     </xs:complexType>
     
     <xs:complexType name="questionType">
         <xs:sequence>
             <xs:element name="answer" type="r:answerType" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="questionID" type="xs:integer"/>
         <xs:attribute name="text" type="xs:string"/>
     </xs:complexType>
     
     <xs:complexType name="answerType">
         <xs:attribute name="answerID" type="xs:integer"/>
         <xs:attribute name="questionID" type="xs:integer"/>
         <xs:attribute name="answerText"/>
         <xs:attribute name="truthValue" type="xs:boolean"/>
     </xs:complexType> 

</xs:schema>

=== johanoeh/publisher_data_access/src/main/resources/file/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:db
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='testspace'
    xsi:schemaLocation='testspace test.xsd'
    dbName="mydb"
    xmlns:ns2="http://www.w3.org/1999/xhtml"
>
    <ns1:person 
            userID="1"
            firstName="jane" 
            middleName="alice"  
            lastName="doe"
            email="jane.doe@gmail.com"
            country="Sweden"
            streetAddress="old road 5"
            city="Stockholm"
            postalCode="958 58"
   />
   
    
    <ns1:person 
        userID="2"
        firstName="john" 
        middleName="michael"  
        lastName="doe"
        email="john.doe@gmail.com"
        country="Sweden"
        streetAddress="old road 5"
        city="Stockholm"
        postalCode="958 58"
    />
    
    
    <ns1:person userID="3"
        firstName="jana" 
        middleName="banana"  
        lastName="doe"
        email="john.doe@gmail.com"
        country="Sweden"
        streetAddress="old road 5"
        city="Stockholm"
        postalCode="958 58" />
    
    <ns1:user 
        userID="1"
        userName="jandoe"
        password="1234"
    />
    <ns1:user 
        userID="2"
        userName="johdoe"
        password="1234"
    />
    <ns1:user 
        userID="3"
        userName="janban"
        password="1234"
    />
    
    <ns1:subject subjectID="1" subjectName="subject one">
        <ns1:descriptionHTML  xmlns="http://www.w3.org/1999/xhtml" > 
            <h1 id="test"> Hello kuk </h1>
        </ns1:descriptionHTML>
        <ns1:chapter chapterID="1" chapterName="chapter one" priority="1">
             <ns1:contentHTML xmlns="http://www.w3.org/1999/xhtml"> 
                <h1> Hello world </h1>
             </ns1:contentHTML>
        </ns1:chapter>
        <ns1:quiz quizID="1" quizName="quiz 1">
             <ns1:question questionID="1" text="Vad är det för skillnad på trä häst">
                <ns1:answer questionID="1" answerID="1" answerText="kan varken cykla" truthValue="true"/>
                <ns1:answer questionID="1" answerID="2" answerText="kan cykla" truthValue="false"/>
            </ns1:question>

        </ns1:quiz>
    </ns1:subject>
    
    <ns1:subject subjectID="2" subjectName="subject one">
        <ns1:descriptionHTML  xmlns="http://www.w3.org/1999/xhtml" > 
            <h1> Hello world </h1>
        </ns1:descriptionHTML>
        <ns1:chapter chapterID="1" subjectID="2" chapterName="chapter one" priority="1">
             <ns1:contentHTML xmlns="http://www.w3.org/1999/xhtml"> 
                <h1> Hello world </h1>
             </ns1:contentHTML>
        </ns1:chapter>
        <ns1:quiz quizID="1" quizName="quiz 1">
            <ns1:question questionID="1" text="Vad är det för skillnad på trä häst">
                <ns1:answer questionID="1" answerID="3" answerText="kan varken cykla" truthValue="true"/>
                <ns1:answer questionID="1" answerID="4" answerText="kan cykla" truthValue="false"/>
            </ns1:question>
        </ns1:quiz>
    </ns1:subject>

</ns1:db>
